# Generated by Django 3.1.4 on 2020-12-16 21:52

import clubs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SR', 'Science and Research'), ('CC', 'Creativity and Culture'), ('SS', 'Social and Student development'), ('EM', 'Entertainment and Media'), ('SD', 'Sports and Dancing'), ('CH', 'Charity')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('AIU', 'AlaToo'), ('KTU', 'Manas'), ('AUCA', 'AUCA'), ('INDPT', 'Independent')], max_length=5)),
                ('image', models.ImageField(upload_to=clubs.models.upload_img)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clubs.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='clubs.university'),
        ),
    ]
