# Generated by Django 3.1.4 on 2020-12-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='clubs.university'),
        ),
    ]
