# Generated by Django 3.1.4 on 2020-12-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20201217_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univ_club', to='clubs.university'),
        ),
    ]
