# Generated by Django 3.1.4 on 2020-12-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20201217_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
