# Generated by Django 3.1.4 on 2020-12-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_projectgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.TextField(default='students'),
        ),
    ]
