# Generated by Django 3.1.4 on 2020-12-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(default='Univer', max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('SR', 'Science and Research'), ('CC', 'Creativity and Culture'), ('SS', 'Social and Student development'), ('EM', 'Entertainment and Media'), ('SD', 'Sports and Dancing'), ('CH', 'Charity'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='university',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
